### ISSUE TITLE
Duplicate keepalived instances running at once

### ISSUE THREAD

**Issue by punassuming** [rvben/rpi-keepalived#2]
When performing this from an RPI, using a single keepalived  container, I notice there are two instances of keepalived running when checking the container service in systemctl.
`docker container ls`

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
22266a5e80af        rvben/rpi-keepalived   "bash -x entrypoint.…"   4 minutes ago       Up 4 minutes                            keepalived
```

```
├─containerd.service
│ ├─ 354 /usr/bin/containerd
│ ├─5872 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.
│ ├─5889 /usr/local/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --log-con
│ └─5919 /usr/local/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --log-con
```

Additionally, it looks like the container is aware of this as well.

`docker container logs keepalived`

```
Sat Mar 28 23:48:14 2020: (VI) WARNING - equal priority advert received from remote host with our IP address.
Sat Mar 28 23:48:15 2020: (VI) WARNING - equal priority advert received from remote host with our IP address.
````

**Comment by rvben** [comment]
Hi @ralesi,

First of all: Thanks a lot for creating this issue and providing all these details.
I hope I can have some time the coming days to troubleshoot this, and I hope to give an update soon.


Kind regards,

Ruben

**Comment by rvben** [comment]
Hi @ralesi,

Again, thanks for bringing this up.
After some research, I found that the two things you're mentioning are not related. The logs showing the error "equal priority advert received from remote host with our IP address" is due to the fact that the UNICAST_PEERS should not include the network interfaces' own ip address, or it will report this warning. 
I fixed that by checking the interfaces' ip address, and preventing from registering it as a unicast peer. This warning should not be shown anymore.

The original issue that "there are two instances of keepalived running", has a different origin. I found  [here ](https://keepalived-devel.narkive.com/BHBVwJ3b/why-keepalived-dont-fork-is-forking-a-child-process) in the keepalived mailinglist, that keepalived spawns a child process, which seems to mean that this is expected behavior.

The warnings should be gone after you update to the latest docker image. Can you please verify this?

**Comment by punassuming** [comment]
Ok, thanks for the good info.  Wasn't aware of this and I should have investigated before raising the issue.  Thanks for looking into it!
